import { CanActivate, ExecutionContext, Injectable, UnauthorizedException, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import type { Request } from 'express';
import type { AppEnv } from '../config/env';
import { PrismaService } from '../prisma/prisma.service';

/**
 * Webhook guard for Evolution. Evolution puts
 * an instance-level `apikey` (UUID generated at create time) into each webhook payload, NOT our global one.
 * So we accept any of:
 *   1. The `apikey` header (when custom headers are configured and forwarded).
 *   2. body.apikey == EVOLUTION_WEBHOOK_SECRET (matches our global).
 *   3. body.apikey matches a known per-instance apikey stored in our DB
 *      (Evolution mints one per instance).
 *   4. The body.instance exists in our DB and the apikey is valid.
 */
@Injectable()
export class WebhookGuard implements CanActivate {
  private readonly logger = new Logger(WebhookGuard.name);

  constructor(
    private readonly config: ConfigService<AppEnv, true>,
    private readonly prisma: PrismaService,
  ) {}

  async canActivate(context: ExecutionContext): Promise<boolean> {
    const req = context.switchToHttp().getRequest<Request>();
    const expected = this.config.get('EVOLUTION_WEBHOOK_SECRET', { infer: true });
    const body = (req.body ?? {}) as { apikey?: unknown; instance?: unknown };
    const fromHeader = req.header('apikey') ?? req.header('x-api-key');
    const fromBody = typeof body.apikey === 'string' ? body.apikey : '';
    const provided = (typeof fromHeader === 'string' && fromHeader) || fromBody || '';

    // 1) Direct match with our global secret
    if (provided && provided === expected) return true;

    // 2) A known instance from our DB. The instance name (n_xxxxxxxx) is generated by
    // our backend and only known to Evolution + us — enough as
    // a first defence layer. If apikey was passed and matches the saved
    // providerKey, that's the second check. If it is not saved yet, persist it.
    if (typeof body.instance === 'string' && body.instance) {
      const number = await this.prisma.whatsappNumber.findUnique({
        where: { wahaSession: body.instance },
        select: { providerKey: true },
      });
      if (number) {
        if (provided && number.providerKey && number.providerKey !== provided) {
          this.logger.warn(`Webhook ${body.instance}: apikey does not match the stored one`);
          throw new UnauthorizedException('Invalid webhook key');
        }
        if (provided && !number.providerKey) {
          await this.prisma.whatsappNumber.update({
            where: { wahaSession: body.instance },
            data: { providerKey: provided },
          });
          this.logger.log(`Saved providerKey for instance ${body.instance}`);
        }
        return true;
      }
    }

    this.logger.warn(`Webhook 401: instance=${body.instance ?? '?'} provided=${provided ? 'set' : 'empty'}`);
    throw new UnauthorizedException('Invalid webhook key');
  }
}
